{% set version = "0.3.2" %}

package:
  name: jupyter_dojo
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter_dojo/jupyter_dojo-{{ version }}.tar.gz
  sha256: a473ba827fcbf8f99c86373c7863b95e308ecc9c9efafe1ddd4180310efcaa8e

build:
  number: 2
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - jupyter nbextension install jupyter_dojo --py --sys-prefix --overwrite

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - ipython_unittest >=0.3
    - notebook >=4.3
    - jupyter
  run:
    - python >={{ python_min }}
    - notebook >=4.3
    - jupyter
    - ipython_unittest

test:
  requires:
    - python {{ python_min }}
  imports:
    - jupyter_dojo

about:
  home: https://github.com/JoaoFelipe/ipython-unittest
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Install the coding dojo extension for ipython_unittest'
  dev_url: https://github.com/JoaoFelipe/ipython-unittest

extra:
  recipe-maintainers:
    - JoaoFelipe
